### ISSUE TITLE
How to print via USB?

### ISSUE THREAD

**Issue by syllasrangel** [fabienbellanger/escpos-rs#10]
I could not find any example of how to print using USB, could you provide an example (preferably on Windows)?
Thank you for your work on this crate.

**Comment by fabienbellanger** [comment]
Hi,
I don't have a USB printer but I will try to get one.
Then I could add a tested example.

**Comment by fabienbellanger** [comment]
I make a quick test with a USB printer on Windows and I think it is not yet possible  :(
I'm going to find a solution but I don't know when I will OK.

**Comment by ldicocco** [comment]
*nix systems view almost everything as a file, so it's possible to use the predefined `FileDriver` to write to USB. This doesn't work on Windows. Anyway, it's just a matter of implementing the `Driver` trait with some library that support multiplatform USB. I think that it should not be too difficult to use this crate. https://crates.io/crates/serialport .
I don't have Windows, but will try to implement a `SerialDriver` with that crate and see if it works on Linux. Hopefully someone can then test it on Windows

**Comment by ldicocco** [comment]
@fabienbellanger  I've just tried using serialport crate, but it worked with Linux and MacOs, but failed to compile on the Raspberry Pi, and I have a heavy dependency on the Raspi. The problem was a dependency on `libudev-sys`, an old crate not maintained anymore.
Anyway, the code was this:
```
pub struct SerialPortDriver {
  path: String,
  port: Rc<RefCell<Box<dyn SerialPort>>>,
}

impl SerialPortDriver {
  pub fn open<'a>(path: &str, baud_rate: u32) -> Result<Self> {
    let port = serialport::new(path, baud_rate).open().unwrap();
    Ok(Self {
      path: path.to_string(),
      port: Rc::new(RefCell::new(port)),
    })
  }
}

impl Driver for SerialPortDriver {
  fn name(&self) -> String {
    format!("file ({})", self.path)
  }

  fn write(&self, data: &[u8]) -> Result<()> {
    self.port.try_borrow_mut()?.write_all(data)?;
    Ok(())
  }

  fn flush(&self) -> Result<()> {
    Ok(self.port.try_borrow_mut()?.flush()?)
  }
}

```

**Comment by ldicocco** [comment]
Hmm. Also [hidapi](https://crates.io/crates/hidapi) has a dependency on libudev and fails to compile on Raspberry Pi. As the Raspi is commonly used with thermal printers, I'd suggest to have a separate crate for direct USB print, that is mainly something necessary on Windows and not on the *nix systems.

**Comment by fabienbellanger** [comment]
I just publish a new release (`0.8.0`) with examples.
@syllasrangel, is it OK for you?

**Comment by syllasrangel** [comment]
Hi @fabienbellanger, thank you very much for adding the USB driver.

I tried the usb example, but I'm getting the following error on Windows:
Uncaught (in promise) IO error: Operation not supported or unimplemented on this platform

Do you have any idea how to resolve this? I'm using the WinUSB driver as recommended here: https://github.com/a1ien/rusb/issues/171

**Comment by syllasrangel** [comment]
> Hi @fabienbellanger, thank you very much for adding the USB driver.
> 
> I tried the usb example, but I'm getting the following error on Windows: Uncaught (in promise) IO error: Operation not supported or unimplemented on this platform
> 
> Do you have any idea how to resolve this? I'm using the WinUSB driver as recommended here: [a1ien/rusb#171](https://github.com/a1ien/rusb/issues/171)

After some investigation I found a possible source for this problem. In https://github.com/fabienbellanger/escpos-rs/blob/3920196af6a27f6ae75a598475b3ff4234a4199f/src/io/driver.rs#L179 you use kernel_driver_active which is not supported on Windows (https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga1cabd4660a274f715eeb82de112e0779).

**Comment by fabienbellanger** [comment]
Hi @syllasrangel
Thanks for your investigation. 
I don't have a Windows environment to test it, but I publish a new release (`0.8.1`) that disable the `kernel_driver_active ` function on Windows.
I hope this will solve your problem.

**Comment by syllasrangel** [comment]
> Hi @syllasrangel Thanks for your investigation. I don't have a Windows environment to test it, but I publish a new release (`0.8.1`) that disable the `kernel_driver_active ` function on Windows. I hope this will solve your problem.

Hi @fabienbellanger, now I run into another problem: Error: Io("Entity not found")

After a quick Google search, I discovered that this error occurs because we need to first claim the interface before operating on it (as also stated here: https://docs.rs/rusb/latest/rusb/struct.DeviceHandle.html#method.claim_interface). 

Adding 
```
device_handle
  .claim_interface(0)
  .map_err(|e| PrinterError::Io(e.to_string()))?;
```
 above the new added line [`#[cfg(not(target_os = "windows"))]`](https://github.com/fabienbellanger/escpos-rs/blob/4708befd2c44a596df06bf24ce2ae66aa16b7aec/src/io/driver.rs#L179) solved the problem for me and I was finally able to print on Windows!

Can you take a look at this and maybe add the claim_interface? I tested only on Windows.

**Comment by fabienbellanger** [comment]
Hi @syllasrangel,
Could you test with this code:
```rust
device_handle
    .claim_interface(endpoint)
    .map_err(|e| PrinterError::Io(e.to_string()))?;
```
instead of:
```rust
device_handle
  .claim_interface(0)
  .map_err(|e| PrinterError::Io(e.to_string()))?;
```
?

**Comment by syllasrangel** [comment]
> Hi @syllasrangel, Could you test with this code:
> 
> ```rust
> device_handle
>     .claim_interface(endpoint)
>     .map_err(|e| PrinterError::Io(e.to_string()))?;
> ```
> 
> instead of:
> 
> ```rust
> device_handle
>   .claim_interface(0)
>   .map_err(|e| PrinterError::Io(e.to_string()))?;
> ```
> 
> ?

Hi @fabienbellanger, it wasn't working because you were claiming the endpoint number, instead of the interface number. I submit a PR with a working version. Please, check the PR https://github.com/fabienbellanger/escpos-rs/pull/15.

**Comment by fabienbellanger** [comment]
@syllasrangel, thank you for your help.
I'll try to test it on MacOS before pushing a release.

**Comment by syllasrangel** [comment]
Thank you @fabienbellanger. I guess now I can close this issue! :)

**Comment by CyJaySong** [comment]
@fabienbellanger Hello, thank you for opening up such an excellent project. I am a Rust beginner and I do not understand the underlying communication principles. I want to call the Rust program to implement cross platform USB ticket printing in an Electron based project, but 'escpos-rs' depends on' libusb'. I don't know how to package 'libusb ' into the project to reduce the process of users installing 'libusb' independently. I have found that [nusb](https://docs.rs/nusb/latest/nusb/index.html) is a pure Rust library. Can escpos-rs rely on connecting to USB printer devices
