### ISSUE TITLE
about usb

### ISSUE THREAD

**Issue by CyJaySong** [fabienbellanger/escpos-rs#17]
@fabienbellanger Hello, thank you for opening up such an excellent project. I am a Rust beginner and I do not understand the underlying communication principles. I want to call the Rust program to implement cross platform USB ticket printing in an Electron based project, but 'escpos-rs' depends on' libusb'. I don't know how to package 'libusb ' into the project to reduce the process of users installing 'libusb'. I have found that [nusb](https://docs.rs/nusb/latest/nusb/index.html) is a pure Rust library. Can escpos-rs rely on `nusb` connecting to USB printer devices

**Comment by fabienbellanger** [comment]
Hi @CyJaySong 
I will take a look at [nusb](https://crates.io/crates/nusb).

**Comment by fabienbellanger** [comment]
@CyJaySong I implemented `nusb` in the `NativeUsbDriver` driver.
The code is available on `nusb` branch.
It seems to be OK on MacOS.
Unfortunately, I don't have Windows environment to test it :(

Would that be right for you?

**Comment by syllasrangel** [comment]
@CyJaySong I think you are mixing two different things. One is the libusb, which is a cross-platform project and they defined themselfs as

> a C library that provides generic access to USB devices. It is intended to be used by developers to facilitate the production of applications that communicate with USB hardware.  (https://libusb.info/)

The other one is the driver itself, which is platform specific. On Windows, libusb can communicate with any of the following drivers:
> Device driver support: WinUSB, HID, libusb-win32 (libusb0.sys, not recommended), libusbK, usbdk. (https://github.com/libusb/libusb/wiki)

Note that libusb-win32 and libusbK are separate projects. That being said, you are probably not looking for an alternative to libusb nor to "package 'libusb' into the project", I assume you are actually looking for a way to automate the driver installation of one of the supported libusb drivers on Windows. This is a problem that nusb will not help with. As said in their documentation:

> To use nusb, your device or interface must be associated with the WinUSB driver. If you control the device firmware, the recommended way is to use a [WCID](https://github.com/pbatard/libwdi/wiki/WCID-Devices) descriptor to tell Windows to install the WinUSB driver automatically when the device is first connected. Alternatively [Zadig](https://zadig.akeo.ie/) (GUI) or [libwdi](https://github.com/pbatard/libwdi) (CLI / C library) can be used to manually install the WinUSB driver for a device.

The difference between rusb and nusb is that rusb relies on the C libusb library, while nusb was written in pure Rust and, apparently, only works with the WinUSB driver.

When it comes to automating the driver installation process, I would say your best call is to take a look at [libwdi](https://github.com/pbatard/libwdi) and look for a way to integrate it into your project.

**Comment by CyJaySong** [comment]
@syllasrangel Have a good day, thanks for your guidance. Reducing reliance on `libusb` will make the call chain simpler. I would like to use Rust to compile the `node module` for `electron` project. I'm not sure how to handle `libusb` when using `rusb`

**Comment by CyJaySong** [comment]
@fabienbellanger  Have a good day, thank you for your help. I will try it out and give you feedback

**Comment by syllasrangel** [comment]
> @syllasrangel Have a good day, thanks for your guidance. Reducing reliance on `libusb` will make the call chain simpler. I would like to use Rust to compile the `node module` for `electron` project. I'm not sure how to handle the `libusb` when iusing `rusb`

Hi @CyJaySong, now I get it. But may I ask, why don't you use [Tauri](https://tauri.app/) instead of electron? I have an Electron project with the exact same purpose as yours (ticket printing), and I use [node-escpos](https://github.com/song940/node-escpos). However, due to many Electron issues, I ended up here. I am now converting my project to [Tauri](https://tauri.app/) + [escpos-rs](https://github.com/fabienbellanger/escpos-rs/), and I am really happy with that change.

**Comment by CyJaySong** [comment]
@syllasrangel  Because my 'Electron' project and 'Web' project share the same code, determining whether the printer function is available by judging the running environment

**Comment by syllasrangel** [comment]
> @syllasrangel Because my 'Electron' project and 'Web' project share the same code, determining whether the printer function is available by judging the running environment

I see, but that is exactly the idea of Tauri. Anyway, did you have success with this new crate?

**Comment by fabienbellanger** [comment]
@CyJaySong I push a new release (`0.10.0`) with the support of `nusb`.
The printer status added in `0.9.0` also works (on MacOS with my printer).
I hope it will OK for you.

**Comment by CyJaySong** [comment]
@fabienbellanger Thank you. I recently underwent surgery due to illness and did not have the opportunity to use a computer for testing. I will forward this message to my colleagues。
