### ISSUE TITLE
Support for printer status

### ISSUE THREAD

**Issue by syllasrangel** [fabienbellanger/escpos-rs#18]
Are there any plans on supporting printer status? Currently, even when the print is not successful we do not get any feedback (e.g., when the printer is connected but there is no paper). For my use case, I need to know whether the print was successful or not. I started looking into the DLE EOT n command (https://download4.epson.biz/sec_pubs/pos/reference_en/escpos/dle_eot.html) and could get the status for my printer but it looks like I am always getting the status from the previous request (when I have time I will do some more tests). But I was wondering, since you already implemented the custom command, I could probably get away with it, but I would need a way to listen back from the printer, do you have any plans on it?

**Comment by fabienbellanger** [comment]
I think it's a geat idea.
I will take a look on it.

**Comment by fabienbellanger** [comment]
Do you have a code example with printer response?
I send a `DLE EOT 1` command to my printer, but I never receive a response.

**Comment by syllasrangel** [comment]
> Do you have a code example with printer response? I send a `DLE EOT 1` command to my printer, but I never receive a response.

I used the read_device example from rusb and added 
```
// Write to the endpoint
let buf_write = [DLE, EOT, 0x1];
match handle.write_bulk(1, &buf_write, timeout) {
    Ok(len) => {
        println!(" - wrote: {:?}", &buf_write[..len]);
    }
    Err(err) => println!("could not write to endpoint: {}", err),
}
```
in https://github.com/a1ien/rusb/blob/29694b99279831745b70975c4f479a80b533b3ee/examples/read_device.rs#L174. I hardcoded the endpoint 1 in the write_bulk because that was my bulk out endpoint.

**Comment by fabienbellanger** [comment]
Hi @syllasrangel, 
I add a new branch `printerStatus` which implements `DLE EOT` command.
I write this example: `status.rs`.
I don't know if that's how you see this feature, so please give me a feedback.
On MacOS, with NetWork and USB driver, the received status seems OK.

**Comment by syllasrangel** [comment]
> Hi @syllasrangel, I add a new branch `printerStatus` which implements `DLE EOT` command. I write this example: `status.rs`. I don't know if that's how you see this feature, so please give me a feedback. On MacOS, with NetWork and USB driver, the received status seems OK.

Hi @fabienbellanger,
Thank you so much for implementing it. That is exactly what I was looking for, I quickly tested it on Windows, and it worked fine. However, I'm still having an issue with some delay in getting the status. I always receive the status from the previous request, not the current one. For example, the first request always returns `InvalidResponse("invalid response pattern: 00000000 (0xx1xx10 expected)")`, and on the second request, I get the status that the printer was in during the request where I received the error. But that may be a problem with my printer. In any case, it is simple to work arround that.

**Comment by fabienbellanger** [comment]
I test with my printer and I don't have the same issue as you.
If it's still OK with you, I'll push a new release.

**Comment by fabienbellanger** [comment]
Issue linked to #19

**Comment by syllasrangel** [comment]
> I test with my printer and I don't have the same issue as you.
> 
> @syllasrangel If it's still OK with you, I'll push a new release.

Hi @fabienbellanger it is ok. Thank you so much for your work on this crate. :)
