### ISSUE TITLE
Is there a plan to TSC label printer support

### ISSUE THREAD

**Issue by CyJaySong** [fabienbellanger/escpos-rs#21]
Is there a plan to TSC label printer support？

**Comment by fabienbellanger** [comment]
Hi @CyJaySong 
Can you give more infirmation about what you want?
What do you need to make your printer work with this crate?
Sorry, I don't a label printer at work :(

**Comment by CyJaySong** [comment]
The 'ESC/POS' instruction set is different from the' TSC 'instruction set and is used for label printers. Perhaps should be created a new 'crate'。
The TSC label printer uses the TSPL command, This is a TSPL related document
https://compex.com.br/wp-content/uploads/servicos_downloads/Impressoras/TSC/Manuais/TSPL_TSPL2_Programming.pdf

**Comment by fabienbellanger** [comment]
Yes, I think it's out of scope of this crate.
A new crate will be the best solution.

**Comment by CyJaySong** [comment]
@fabienbellanger 

> 是的，我认为它超出了这个箱子的范围。 一个新的箱子将是最好的解决方案。

Yes, I think so
