### ISSUE TITLE
Do you plan to create a new crate for TSC label printer

### ISSUE THREAD

**Issue by CyJaySong** [fabienbellanger/escpos-rs#24]
We have previously discussed that this library is not suitable for adding `TSPL` command support. Do you have plan to create a new crate  for TSC label printers support?

**Comment by fabienbellanger** [comment]
Hi,
Unfortunately, I don't plan to create a new crate for TSC label printer at the moment.

**Comment by CyJaySong** [comment]
Okay, thank you😀
