### ISSUE TITLE
Specifying baud rate 

### ISSUE THREAD

**Issue by ldicocco** [fabienbellanger/escpos-rs#26]
Is it possible to specify the baud rate with drivers different from SerialPortDriver?

**Comment by fabienbellanger** [comment]
Hi,
Currently, only Serial port driver can specify a baud rate.
I will see if I can add it to USB drivers.

**Comment by fabienbellanger** [comment]
I've had a look at `rusb`, `nusb` and `hidapi` crates and it doesn't seem to be possible to specify the baud rate.

**Comment by ldicocco** [comment]
> I've had a look at `rusb`, `nusb` and `hidapi` crates and it doesn't seem to be possible to specify the baud rate.

Yes. I already looked at them and it looked the same to me. But I'm not an expert and I thought that maybe I was missing something.
For my part, this was a nice to have but not something necessary to continue using this wonderful crate.
Thank you.
