### ISSUE TITLE
Implementing Copy and Clone for the JustifyMode enum

### ISSUE THREAD

**Issue by travisbaars** [fabienbellanger/escpos-rs#3]
First off, I would like to thank you for putting this library together. I found it much better than the other options. 

Now I'm no Rust expert but I was working on a simple GUI app that utilizes this crate. In doing so I ran into an issue where I needed `JustifyMode`  to implement the `Copy` and `Clone`  traits.

The code in question is in [types.rs](https://github.com/fabienbellanger/escpos-rs/blob/8aec436685177ae2f8d3c8353533981fbb1e133a/src/domain/types.rs)

Here is a simple example that causes the issue:

```rust
use escpos::utils:*;

struct Demo {
    j: JustifyMode,
}

impl Demo {
    fn temp(&self) {
        self.j;
    }
}

fn main() {
    // code omitted here for simplicity
}
```

The error it produces is:

```
cannot move out of `self.j` which is behind a shared reference
move occurs because `self.j` has type `escpos::utils::JustifyMode`, which does not implement the `Copy` trait
```

## Current code

```rust
/// Justify mode
#[derive(Debug)]
pub enum JustifyMode {
    LEFT,
    CENTER,
    RIGHT,
}
```

## Proposed change

```rust
/// Justify mode
#[derive(Debug, Clone, Copy)]
pub enum JustifyMode {
    LEFT,
    CENTER,
    RIGHT,
}
```

I have a fork where I have made these changes. Let me know and I can make a Pull Request.

If this is not needed because there is a better way to do it, please let me know.

Thanks again for your work here!

**Comment by fabienbellanger** [comment]
Hi,

Yes, of course!
We can add `Clone` and `Copy` traits to `CashDrawer` and `JustifyMode` structures.

You can make a PR 👍

**Comment by fabienbellanger** [comment]
I've just published the changes on crates.io in version 0.6.2 😄
